// -----------------------------------------------------------------------------
// ⚠️ AUTO-GENERATED FILE
// This file is generated by a script. Do not edit manually.
// Instead, modify the package.json files under /src/chapters
// and re-run the generator.
// -----------------------------------------------------------------------------

export const chapterInputs = {
    'template': '@w3gallery/template#^0.1.0-wip',
    'tdse-1d': '@w3gallery/tdse-1d#^0.1.0-wip',
}
