// -----------------------------------------------------------------------------
// ⚠️ AUTO-GENERATED FILE
// This file is generated by a script. Do not edit manually.
// Instead, modify the package.json files under /src/chapters
// and re-run the generator.
// -----------------------------------------------------------------------------

export const chapterInputs = {
    'template': '@w3gallery/template#^0.1.0-wip',
    'hello-vs-flow': '@w3gallery/hello-vs-flow#^0.1.0-wip',
    'openalea': '@w3gallery/openalea#^0.1.0',
    'tdse-1d': '@w3gallery/tdse-1d#^0.1.0-wip',
    'cpp-notebook': '@w3gallery/cpp-notebook#^0.1.0-wip',
}
